name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Plenary Busted Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: vimed.nvim
      - name: Setup `nui.nvim`
        uses: actions/checkout@v2
        with:
          repository: MunifTanjim/nui.nvim
          path: nui.nvim
      - name: Setup `plenary.nvim`
        uses: actions/checkout@v2
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - name: Install Neovim
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:neovim-ppa/unstable
          sudo apt-get install neovim
      - name: Run Tests
        run: |
          cd vimed.nvim
          make setup-ci
          make test
